version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      development:
        patterns:
          - "ruff"
          - "pytest*"
          - "mypy"
      litex:
        patterns:
          - "litex*"
          - "migen"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"