//--------------------------------------------------------------------------------
// Auto-generated by LiteX (f935697) on 2025-06-29 19:16:30
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef MAIN_RAM_BASE
#define MAIN_RAM_BASE 0x40000000L
#define MAIN_RAM_SIZE 0x00002000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "MAIN_RAM  0x40000000 0x2000 \nCSR       0x00000000 0x10000 "
#endif
#endif
