//--------------------------------------------------------------------------------
// Auto-generated by LiteX (98c683b) on 2025-06-30 16:46:51
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "alinx_axau15"
#define CONFIG_CLOCK_FREQUENCY 180000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY
#define CONFIG_CPU_NAME
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define CONFIG_BIOS_NO_BUILD_TIME
#define CONFIG_IDENTIFIER "LiteX SoC on Alinx AXAU15"
#define DMA_CHANNELS 1
#define DMA_ADDR_WIDTH 32
#define PCIE_DMA0_READER_INTERRUPT 0
#define PCIE_DMA0_WRITER_INTERRUPT 1
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0

#endif
